version: "3"

services:
  web:
    container_name: acy_website
    restart: always
    build: .
    ports:
      - "5000:5000"

    volumes:
      - ./build:/code/build
      - ./public:/code/public
      - ./src:/code/src
      - ./node_modules:/code/node_modules
